#!/usr/bin/env bash
# Installs HAProxy version 2.8 LTS with the following configurations:
#    Enables management via the init script.
#    Distributes requests using a round-robin algorithm.

apt-get install -y software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get update
apt-get install -y haproxy=2.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg
ss
printf %s "sglobal
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeoust server  10000

listen hbnb
    bind *:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 431135-web-01 34.207.121.4:80 check
    server 431135-web-02 52.3.246.225:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
