#!/usr/bin/env bash
# A script that prints 'Best School' 10 times and hi in the new line after 9th iteration. using if

i=1

while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i  -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done

