#!/usr/bin/env bash
# this changes the hosts files in the system. acountng for docker spacefic case

cp /etc/hosts ~/hosts.new
echo "127.0.0.2         localhost" > ~/hosts.new
echo "8.8.8.8           facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
